name: CI Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Enable long paths on Windows
        run: git config --global core.longpaths true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test,examples]
          python -m ipykernel install --user --name python3

      - name: Test with unittest
        env:
          HED_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m unittest discover tests
